---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${cluster-name-short}-cert-manager
  namespace: argocd
  labels:
    solo.io/infra: cert-manager
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    targetRevision: v1.9.1
    chart: cert-manager
    helm:
      values: |
        installCRDs: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 
    syncOptions:
    - CreateNamespace=false
  destination:
    server: ${ destination-server }
    namespace: kube-system  