apiVersion: security.policy.gloo.solo.io/v2
kind: ExtAuthPolicy
metadata:
  name: opa-sidecar
  namespace: httpbin
spec:
  applyToDestinations:
  - selector:
      labels:
        app: httpbin
  config:
    server:
      name: opa-ext-auth-server
      namespace: httpbin
    glooAuth:
      configs:
      - opaServerAuth:
          package: httpbin
          ruleName: allow/allowed